import os
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from model import load_tokenizer, load_model, generate_medical_response
from groq import Groq

app = FastAPI()

tokenizer = load_tokenizer()
model = load_model()

groq_client = Groq(api_key="YOUR_GROQ_API")

SYSTEM_PROMPT = """You are VitalLM, a professional and empathetic AI medical assistant.

You will receive a patient's message and a raw draft response generated by a small medical language model.
Your job is to:
1. Carefully read the patient's concern
2. Use the raw draft as a loose reference for medical direction only
3. Write a clean, warm, professional doctor's response
4. Structure your response as:
   - Brief acknowledgment of the patient's concern
   - Most likely explanation or diagnosis
   - Practical advice or next steps
   - When to seek emergency care (if relevant)
   - Closing encouragement

Rules:
- Never mention that you used a draft or raw model output
- Never say "I am an AI" or "I cannot provide medical advice" — just be helpful
- Keep response under 200 words
- Use plain English, avoid excessive jargon
- Never make up medications or dosages
- Always recommend consulting a doctor for serious concerns"""


def polish_with_groq(raw_response: str, original_prompt: str) -> str:
    try:
        completion = groq_client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": f"""Patient message:
{original_prompt}

Raw draft response to use as medical reference:
{raw_response}

Write a clean, professional doctor's response to the patient."""}
            ],
            temperature=0.4,
            max_tokens=400,
            top_p=0.9,
            frequency_penalty=0.3,
            presence_penalty=0.2,
        )
        return completion.choices[0].message.content.strip()

    except Exception as e:
        # Fallback: return cleaned raw response if Groq fails
        return raw_response


class Prompt(BaseModel):
    message: str


@app.get("/")
def root():
    return {"status": "VitalLM API is running", "endpoints": ["/chat", "/health"]}


@app.get("/health")
def health():
    return {"status": "ok", "model": "VitalLM-50M + Groq LLaMA-3.3-70B"}


@app.post("/chat")
def chat(prompt: Prompt):
    if not prompt.message.strip():
        raise HTTPException(status_code=400, detail="Message cannot be empty")

    if len(prompt.message) > 1000:
        raise HTTPException(status_code=400, detail="Message too long. Max 1000 characters.")

    # Format prompt if not already in Patient/Doctor format
    message = prompt.message.strip()
    if not message.lower().startswith("patient:"):
        message = f"Patient: {message} Doctor:"

    # Step 1: Local SLM generates raw medical draft
    raw = generate_medical_response(model, tokenizer, message)

    # Step 2: Groq polishes into final response
    final = polish_with_groq(raw, prompt.message)

    return {
        "prompt": prompt.message,
        "raw_response": raw,
        "groq_response": final
    }